
;--------------------------------------
;--------------------------------------
                * = $3000
;--------------------------------------

csetMountains   .byte $00,$00,$50,$A5,$AA,$AA,$AA,$AA
                .byte $00,$01,$06,$5A,$AA,$AA,$AA,$AA
                .byte $00,$50,$A4,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$54,$A9,$AA,$AA
                .byte $00,$00,$00,$00,$00,$41,$96,$AA
                .byte $00,$00,$00,$00,$05,$5A,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A4,$A9
                .byte $00,$00,$00,$00,$00,$00,$05,$5A
                .byte $00,$00,$00,$00,$01,$16,$6A,$AA
                .byte $00,$00,$00,$00,$50,$A4,$A9,$AA
                .byte $00,$00,$00,$00,$01,$16,$6A,$AA
                .byte $00,$05,$1A,$6A,$AA,$AA,$AA,$AA
                .byte $00,$40,$94,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$40,$94,$A9,$AA,$AA
                .byte $00,$00,$00,$00,$00,$40,$95,$AA
                .byte $00,$00,$00,$00,$01,$56,$AA,$AA
                .byte $00,$00,$15,$6A,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$40,$90,$A4,$A9,$AA
                .byte $00,$00,$00,$00,$00,$05,$5A,$AA
                .byte $00,$00,$00,$05,$1A,$6A,$AA,$AA
                .byte $00,$00,$05,$5A,$AA,$AA,$AA,$AA
                .byte $00,$00,$55,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$54,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A5,$AA
                .byte $00,$00,$00,$00,$00,$05,$5A,$AA
                .byte $01,$06,$1A,$1A,$6A,$AA,$AA,$AA
                .byte $50,$A5,$AA,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$A5,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$50,$A4,$A9,$AA
                .byte $00,$01,$06,$06,$1A,$6A,$AA,$AA
                .byte $50,$A4,$A9,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$41,$96,$AA,$AA
                .byte $00,$00,$01,$06,$5A,$AA,$AA,$AA
                .byte $00,$15,$6A,$AA,$AA,$AA,$AA,$AA
                .byte $00,$50,$A4,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$40,$95,$AA
                .byte $00,$00,$00,$01,$01,$06,$5A,$AA
                .byte $00,$05,$5A,$AA,$AA,$AA,$AA,$AA
                .byte $00,$40,$90,$A4,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$14,$69,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$05,$5A,$AA,$AA
                .byte $00,$00,$01,$16,$6A,$AA,$AA,$AA
                .byte $00,$15,$6A,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$A4,$A9,$AA,$AA
                .byte $00,$00,$00,$01,$06,$5A,$AA,$AA
                .byte $00,$01,$56,$AA,$AA,$AA,$AA,$AA
                .byte $54,$A9,$AA,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$50,$A4,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$00,$41,$96,$AA
                .byte $00,$00,$00,$00,$15,$6A,$AA,$AA
                .byte $00,$00,$00,$00,$00,$41,$96,$AA
                .byte $00,$01,$06,$1A,$6A,$AA,$AA,$AA
                .byte $00,$40,$94,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A4,$A9
                .byte $00,$00,$00,$00,$00,$01,$16,$6A
                .byte $00,$00,$00,$00,$50,$A5,$AA,$AA
                .byte $00,$00,$00,$00,$50,$A4,$A9,$AA
                .byte $01,$06,$06,$06,$1A,$6A,$AA,$AA
                .byte $40,$94,$A9,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$94,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$50,$A5,$AA,$AA
                .byte $01,$06,$1A,$1A,$6A,$AA,$AA,$AA
                .byte $50,$A4,$A9,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$55,$AA,$AA,$AA,$AA,$AA
                .byte $00,$15,$6A,$AA,$AA,$AA,$AA,$AA
                .byte $00,$40,$94,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$40,$95,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$50,$A5,$AA,$AA
                .byte $00,$00,$00,$00,$00,$41,$96,$AA
                .byte $00,$00,$00,$00,$05,$5A,$AA,$AA
                .byte $00,$00,$05,$1A,$6A,$AA,$AA,$AA
                .byte $00,$00,$41,$96,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$90,$A4,$A9,$AA
                .byte $00,$00,$00,$00,$00,$00,$05,$5A
                .byte $00,$00,$00,$00,$01,$06,$5A,$AA
                .byte $00,$00,$00,$51,$A6,$AA,$AA,$AA
                .byte $00,$00,$50,$A4,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A5,$AA
                .byte $00,$00,$00,$00,$05,$1A,$6A,$AA
                .byte $00,$01,$06,$1A,$6A,$AA,$AA,$AA
                .byte $55,$AA,$AA,$AA,$AA,$AA,$AA,$AA
                .byte $40,$94,$A9,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$94,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$55,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$41,$96,$AA,$AA
                .byte $00,$00,$01,$56,$AA,$AA,$AA,$AA
                .byte $00,$15,$6A,$AA,$AA,$AA,$AA,$AA
                .byte $00,$50,$A4,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$41,$96,$AA,$AA
                .byte $00,$05,$1A,$6A,$AA,$AA,$AA,$AA
                .byte $00,$40,$90,$A4,$A9,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A5,$AA
                .byte $01,$06,$06,$1A,$1A,$6A,$AA,$AA
                .byte $40,$94,$A9,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$40,$95,$AA,$AA,$AA
                .byte $00,$00,$01,$06,$5A,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$90,$A4,$A9,$AA
                .byte $00,$00,$00,$00,$00,$00,$55,$AA
                .byte $00,$00,$00,$00,$05,$5A,$AA,$AA
                .byte $00,$00,$05,$1A,$6A,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$A5,$AA,$AA,$AA
                .byte $01,$06,$1A,$6A,$AA,$AA,$AA,$AA
                .byte $40,$90,$A5,$AA,$AA,$AA,$AA,$AA
                .byte $00,$00,$41,$96,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$90,$A4,$A9,$AA,$AA
                .byte $00,$00,$00,$00,$05,$5A,$AA,$AA
                .byte $00,$00,$00,$00,$40,$90,$A4,$A9
                .byte $00,$00,$00,$00,$00,$01,$16,$6A
                .byte $00,$00,$01,$06,$1A,$6A,$AA,$AA
                .byte $00,$00,$40,$90,$A4,$A9,$AA,$AA
                .byte $00,$00,$00,$00,$01,$56,$AA,$AA
                .byte $00,$00,$00,$00,$50,$A5,$AA,$AA
                .byte $00,$00,$00,$00,$00,$41,$96,$AA
                .byte $01,$06,$1A,$1A,$1A,$6A,$AA,$AA
                .byte $55,$AA,$AA,$AA,$AA,$AA,$AA,$AA
                .byte $00,$40,$94,$A9,$AA,$AA,$AA,$AA
                .byte $00,$00,$00,$00,$40,$94,$A9,$AA
                .byte $00,$00,$00,$00,$01,$06,$5A,$AA
                .byte $01,$06,$1A,$1A,$6A,$AA,$AA,$AA
                .byte $40,$90,$A4,$A9,$AA,$AA,$AA,$AA
                .byte $00,$05,$1A,$6A,$AA,$AA,$AA,$AA
                .byte $00,$40,$90,$90,$A4,$A4,$A9,$AA
                .byte $00,$00,$00,$00,$00,$00,$41,$96
                .byte $00,$00,$00,$00,$00,$50,$64,$A9
                .byte $00,$00,$00,$00,$01,$06,$1A,$6A
                .byte $00,$00,$05,$5A,$AA,$AA,$AA,$AA
                .byte $00,$00,$40,$94,$A9,$AA,$AA,$AA
                .byte $00,$00,$01,$16,$6A,$AA,$AA,$AA

; .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... ...g gg.. .... .... .... gg.. .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... ggg. .... .... .... .... .... .... .... .... .... .... ...g g... .... .... ...g gg.. .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... .... gggg g... .... .... .... .... .... .... .... .... .... .... ...g g... .... .... .... .... .... .... .... ...g g... .... .... .... .... .... .... .... .... .... .... ...g gggg .... .... .... ...g g... .... .... .... .... .... .... .... ....
; .... ...g gg.. .... .... .... .... .... .... .... .... ..gg g... .... .... .... .... .... .... .... .... .... .... .... .... ..gR RRgg .... .... ...g RRg. .... .... .ggg gg.. .... .... ..gg g... .... .... .... .ggg .... .... ...g RRRg .... .... .... .... ...g g... .... .... .... .... ..gR Rgg. .... .... ..gR RRg. .... .ggg g... .... .... .... .... .... .... .... .... .... .... .... .... .... ...g RRRR Rgg. .... .... .... .... .ggg gg.. .... ..gg g... .... ..gR Rgg. .... .... .... .... .... .... .... ..gR Rg.. .... .... .... .... .... .... .... .... .... .... ..gR RRRR g... .... .... ..gR Rg.. ..gg g... .... .... .... .... .... ....
; gg.. ..gR RRg. .... .... .... .... .... .... .... .... .gRR Rgg. .... .... .... .ggg .... .... .... ..gg gggg .... .... .... .gRR RRRR g... .... ..gR RRRg .... ...g gRRR RRg. .... .... ggRR Rg.. .... .... ...g gRRR g... .... gggR RRRR gg.. .... .... .... ..gR Rgg. .... .... .... .... ..gR RRRg g... .... .gRR RRRg gggg gRRR Rgg. .... .... .... .... ..gg g..g g... .... .... .... gg.. .... .... ..gR RRRR RRRg g... .... .... ...g gRRR RRg. .... .gRR Rg.. .... ..gR RRRg .... ...g g... .... .... ..gg g... .gRR RRgg g..g g... .... .... .... ...g g... .... .... .... .gRR RRRR Rgg. .... .... .gRR RRg. .gRR Rg.. .... .... .... ..gg g... ...g
; RRgg ggRR RRRg .... .... .... .... .... .... .... .... gRRR RRRg g... .... .... gRRR g... .... ..gg ggRR RRRR ggg. .... .... .gRR RRRR Rg.. .... ..gR RRRg .... ..gR RRRR RRRg .... ...g RRRR RRg. .gg. .... .ggR RRRR Rg.. ...g RRRR RRRR RRg. .... .... .... .gRR RRRg .... .... .... .... ..gR RRRR Rgg. .... .gRR RRRR RRRR RRRR RRRg g... .... .... .... .gRR RggR Rg.. .... .... gg.g RRg. .... .... .gRR RRRR RRRR Rgg. .... .... gggR RRRR RRRg .... gRRR RRg. .... .gRR RRRR g... ..gR Rg.. .... .... .gRR Rg.. gRRR RRRR RggR Rg.. .... .... .... ..gR Rg.. .... .... .... .gRR RRRR RRRg .... .... .gRR RRRg gRRR Rg.. .... .... .... ggRR Rgg. .ggR
; RRRR RRRR RRRR ggg. .... ..gg g... .... ...g gg.. ...g RRRR RRRR Rgg. .... ...g RRRR Rg.. .... .gRR RRRR RRRR RRRg g... .... gRRR RRRR RRgg gg.. .gRR RRRR g..g ggRR RRRR RRRR g... ...g RRRR RRRg gRRg ..gg gRRR RRRR RRg. ..gR RRRR RRRR RRRg .... .ggg .... gRRR RRRR g... .... gg.. gg.. .gRR RRRR RRRg gg.. gRRR RRRR RRRR RRRR RRRR Rggg gg.. .... ..gg gRRR RRRR Rg.. .... ...g RRgR RRRg g... ..gg gRRR RRRR RRRR RRRg gggg g..g RRRR RRRR RRRR g..g RRRR RRRg g... .gRR RRRR Rggg ggRR Rg.. .... ..gg gRRR RRgg RRRR RRRR RRRR RRg. ..gg g... .... .gRR RRg. ...g gg.. .... .gRR RRRR RRRR g... ...g gRRR RRRR RRRR RRg. .... .... ...g RRRR RRRg gRRR
; RRRR RRRR RRRR RRRg g..g ggRR Rg.. .... .ggR RRg. .ggR RRRR RRRR RRRg g... gggR RRRR RRg. ..gg gRRR RRRR RRRR RRRR Rg.. ..gg RRRR RRRR RRRR RRg. gRRR RRRR RggR RRRR RRRR RRRR g... ..gR RRRR RRRR RRRR ggRR RRRR RRRR RRRg ggRR RRRR RRRR RRRR g..g gRRR g..g RRRR RRRR Rg.. ...g RRgg RRg. gRRR RRRR RRRR RRgg RRRR RRRR RRRR RRRR RRRR RRRR RRgg g..g ggRR RRRR RRRR RRg. .... ..gR RRRR RRRR Rg.. .gRR RRRR RRRR RRRR RRRR RRRR RggR RRRR RRRR RRRR RggR RRRR RRRR Rg.. gRRR RRRR RRRR RRRR RRg. .... ggRR RRRR RRRR RRRR RRRR RRRR RRRg ggRR Rg.. ...g gRRR RRRg gggR RRgg g..g gRRR RRRR RRRR Rgg. ..gR RRRR RRRR RRRR RRg. .... gg.. ..gR RRRR RRRR RRRR
; RRRR RRRR RRRR RRRR RggR RRRR RRg. ..gg gRRR RRRg gRRR RRRR RRRR RRRR Rggg RRRR RRRR RRRg ggRR RRRR RRRR RRRR RRRR RRgg ggRR RRRR RRRR RRRR RRRg RRRR RRRR RRRR RRRR RRRR RRRR Rggg ggRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RggR RRRR RggR RRRR RRRR RRg. .ggR RRRR RRRg RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RggR RRRR RRRR RRRR RRRg ..gg ggRR RRRR RRRR RRgg gRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRgg RRRR RRRR RRRR RRRR RRRg gggg RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRg. .ggR RRRR RRRR RRRR RRRR RggR RRRR RRRR RRRR RRRg ggRR RRRR RRRR RRRR RRRg g..g gRg. .gRR RRRR RRRR RRRR
; RRRR RRRR RRRR RRRR RRRR RRRR RRRg ggRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRg gRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR ggRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRg gRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RRRR RggR RRRg gRRR RRRR RRRR RRRR
